# Config Yaml.
# 
# Info.
# Both `decrypt` and `encrypt` are an array of objects.
# Each element in array is an object with two sub fields: 
# - src : specify a path to a source file you want to decrypt/encrypt.
# - out : specify a path where the encrypted/decrypted file should be written to.
#
# Leave decrypt/encrypt field as an empty array to skip the enc/dec task.

# Enqueue following files for decrypt.
decrypt: 
    # Ver - 413
  - src: 'C:\Projects\playground\system-hf-p5\chargrp.dat'
    out: 'C:\Projects\playground\system-hf-p5-dec\dec-chargrp.dat'
    # Ver - 413
  - src: 'C:\Projects\playground\system-hf-p5\armorgrp.dat'
    out: 'C:\Projects\playground\system-hf-p5-dec\dec-armorgrp.dat.dat'

# Enqueue following files for encrypt.
encrypt: []